## Ground Dataset Initial Feature Extraction 
Testing ground with a sample from the ground set; the actual execution is in APS_FEATURES_INITIAL.py

In [2]:
import re 
import pandas as pd 
import tqdm 
from nltk.util import bigrams

nupos_classes = {
    "acp": "acp word as adverb; adv/conj/pcl/prep",
    "pf": "preposition of",
    "pi": "indefinite pronoun",
    "pn": "personal pronoun",
    "po": "possessive pronoun",
    "pp": "preposition",
    "pu": "punctuation",
    "px": "reflexive pronoun",
    "sy": "symbol",
    "uh": "interjection",
    "va": "auxiliary verb",
    "vm": "modal verb",
    "v": "verb",
    "xx": "negative",
    "zz": "undetermined",
    "an": "adverb/noun",
    "av": "adverb",
    "cc": "coordinating conjunction",
    "crq": "wh-word",
    "cs": "subordinating conjunction",
    "d": "determiner",
    "fw": "foreign word",  
    "j": "adjective",
    "np": "proper noun",
    "n": "noun",
    "crd": "numeral"
}
content = ['an', 'av','fw','j', 'np', 'n', 'crd','va', 'vm', 'v']
function = ['acp', 'cc', 'crq', 'cs', 'd', 'pf', 'pi', 'pn', 'po', 'pp', 'pu', 'px', 'sy', 'uh', 'xx', 'zz']
content = "|".join(content)
function = "|".join(function)

fname = "../CORPUS/APS_TEXTS_ground.csv"
texts = pd.read_csv(fname).to_dict(orient='records')

In [1]:
from nltk import ngrams
from collections import Counter 

# test case for POS bigrams and lemmata character 4-grams 
pos = "<s> np1 np1 pp-f dt njp n1 , cc dt n1 pp-f po31 n2 </s> <s> <i> fw-la . </s> <s> </i>"
pos_bigrams = ["_".join(n) for n in ngrams(pos.split(), 2) if not ("<" in n[0] and "<" in n[1])]
print(pos_bigrams)
lemmata = "<s> Chap. I. of the christian doctrine , and the number of its division ........................ </s> <s> <i> ibid . </s> <s> </i>"
chars = []
for word in lemmata.lower().split(): 
    if "<" in word and ">" in word: 
        chars.append(word)
    elif ".." not in word: 
        for c in word: 
            chars.append(c)
    chars.append("_")
chars = chars[:-1]
char_4grams = ["".join(n) for n in ngrams(chars, 4) if len([x for x in n if "<" in x]) < 2]
print(Counter(char_4grams).most_common(n=10))

['<s>_np1', 'np1_np1', 'np1_pp-f', 'pp-f_dt', 'dt_njp', 'njp_n1', 'n1_,', ',_cc', 'cc_dt', 'dt_n1', 'n1_pp-f', 'pp-f_po31', 'po31_n2', 'n2_</s>', '<i>_fw-la', 'fw-la_.', '._</s>']
[('_of_', 2), ('_the', 2), ('the_', 2), ('<s>_ch', 1), ('_cha', 1), ('chap', 1), ('hap.', 1), ('ap._', 1), ('p._i', 1), ('._i.', 1)]

In [131]:
import spacy
NER = spacy.load('en_core_web_sm')
# test out NER with spacy 
sample = "<s> The tenor of the decree in its promulgation ( which was the other point to be proved ) is uniformly conditional . </s> <s> Gen. ii . </s> <s> 17. </s> <s> <i> thou shalt not eat of it ; for in the day that thou eatest thereof thou shalt surely die , — </i> which is the same as if God had said , I will that thou shalt not eat of it ; I have not therefore decreed that thou shalt eat of it ; for if thou eat , thou shalt die ; if thou eat not , thou shalt live . </s> <s> Thus the decree itself was conditional before the fall ; which from numberless other passages appears to have been also the case after the fall . </s> <s> Gen. iv . </s> <s> 7. </s> <s> <i> if thou doest well , shalt thou not be accepted ? and if thou doest not well , sin lieth at the door , </i> or , <i> the punishment of sin watcheth for thee . </s> <s> </i> Exod. xxxii . </s> <s> 32 , 33. </s> <s> <i> blot me , I pray thee , out of thy book which thou hast written ...... whosoever hath sinned against me , him will I blot out of my book . </s> <s> </i> Such was the love of Moses for his nation , that he either did not remember that believers , so long as they continued such , could not be blotted out , or the expression must be understood in a modified sense , as in Rom. ix . </s> <s> 1 , &c. </s> <s> ; <i> I could wish , if it were possible — : </i> but the answer of God , although metaphorical , explains with sufficient clearness that the principle of predestination is founded upon a condition , — <i> whosoever hath sinned , him will I blot out . </s> <s> </i> This is announced more fully in the enforcement of the legal covenant , Deut. vii . </s> <s> 6 — 8. where God particularly declares his choice and love of his people to have been gratuitous ; and in v. 9. where he desires to be known as <i> a faithful God which keepeth his covenant and mercy , </i> he yet adds as a condition , <i> with them that love him and keep his commandments . </s> <s> </i> Again , it is said still more clearly , v. 12. </s> <s> <i> it shall come to pass , if ye hearken to these judgements , and keep and do them , that Jehovah thy God shall keep unto thee the covenant and the mercy which he sware unto thy fathers . </s> <s> </i> Though these and similar passages seem chiefly to refer either to the universal election of a nation to the service of God , or of a particular individual or family to some office ( for in the Old Testament it is perhaps difficult to trace even a single expression which refers to election properly so called , that is , election to eternal life ) , yet the principle of the divine decree is in all cases the same . </s> <s> Thus it is said of Solomon , as of another Christ , 1 Chron. xxviii . </s> <s> 6 , 7 , 9. </s> <s> <i> I have chosen him to be my son , and I will be his father . </s> <s> </i> But what are the terms of the covenant ? — <i> if he be constant to do my commandments and my judgements , as at this day … … if thou seek him , he will be found of thee ; but if thou forsake him , he will cast thee off for ever . </s> <s> </i> The election of his posterity also depended on the same stipulation . </s> <s> 2 Chron. vi . </s> <s> 16. </s> <s> <i> so that thy children take heed to their way , to walk in my law . </s> <s> </i> See also xxxiii . </s> <s> 8. and xv . </s> <s> 2. </s> <s> <i> the Lord is with you , while ye be with him … … but if ye forsake him , he will forsake you ; </i> whence Isaiah does not scruple to say , xiv . </s> <s> 1 , <i> the Lord will yet choose Israel . </s> <s> </i> See also Zech. i . </s> <s> 16. </s> <s> Isaiah also shows who are the elect ; lxv . </s> <s> 9 , 10. </s> <s> <i> mine elect shall inherit it … … and Sharon shall be … … for my people that have sought me . </s> <s> </i> Jer. xxii . </s> <s> 24. </s> <s> <i> though Coniah were the signet upon my right hand , yet would I pluck thee thence . </s> <s> </i>"
doc = NER(sample.lower())
entities = {}
for ent in doc.ents:
    ent = ent.label_
    if ent not in entities: entities[ent] = 0 
    entities[ent] += 1 
    # items = [ent.text, ent.label_]
    # entities.append(" | ".join([str(i) for i in items]))
print(entities)

{'CARDINAL': 17, 'DATE': 4, 'GPE': 6, 'NORP': 1, 'PERSON': 5}

In [ ]:
def replace(pattern, str): 
    str = re.sub(pattern," ",str)
    str = re.sub(r"\s+"," ",str).strip()
    return str 

def get_spans(pattern,tokens,pos,lemmata): 
    one = re.findall(pattern,tokens)
    two = re.findall(pattern,pos)
    three = re.findall(pattern,lemmata)
    return one,two,three

def reinitiate_features(): 
    features = {}
    features["num_tokens"] = 0 # equivalent to DIV length
    features["num_types"] = set() # convert to int length later
    features["sentence_length"] = [] # take the mean later 
    features['content'] = 0 
    features['function'] = 0 # not counting punctuation 
    features['punctuation'] = 0 # includes boundaries 
    features["female_pronouns"] = 0 
    features["male_pronouns"] = 0 
    features["plural_pronouns"] = 0 
    features.update({pos:0 for pos in nupos_classes})
    return features 
def reinitiate_spans(): 
    return {'tokens':"",'pos':"","lemmata":""}

def count_feature(lemma,pos,features): 
    features['num_tokens'] += 1 
    if lemma.lower() == "she": 
        features["female_pronouns"] += 1 
    elif lemma.lower() == "he": 
        features["male_pronouns"] += 1 
    elif lemma.lower() == "they": 
        features["plural_pronouns"] += 1 
    if lemma == pos: # punctuation 
        if lemma not in features: 
            features[lemma] = 0
        features[lemma] += 1 
        features['punctuation'] += 1 
    elif re.search(content,pos):
        features['content'] += 1 
    else: 
        features['function'] += 1  
    for item in nupos_classes: 
        if item in pos: 
            features[item] += 1 
            # can only be in one class 
            break
    return features 

def update_span(span_dict, t,p,l): 
    span_dict['tokens'] += " {}".format(t.lower())
    span_dict['pos'] += " {}".format(p.lower())
    span_dict['lemmata'] += " {}".format(l.lower())
    return span_dict 

FEATURES_DICT = {} # key (tcpID, DIV_idx), value is the features dict 
VOCAB = {'content':{},
         'function':{},
         'punctuation':{}} # to determine high-frequency words 
SPANS = { # spans 
        '<l>': {}, 
        '<i>': {},
        '<n>': {},
        'np': {},
    } 
GRAMS = {
        'char4grams': {},
        'pos2grams': {},
        'entities':{}
    }
entities = set()
for idx, entry in tqdm.tqdm(enumerate(texts)): 
    # if entry['tcpID'] != "DDC_FINAL": continue 
    key = (entry['tcpID'],entry['curr_div_idx']) 
    if key not in FEATURES_DICT: 
        # tally features for each separate DIV 
        FEATURES_DICT[key] = reinitiate_features()
    # get POS bigrams
    pos2grams = ["_".join(n) for n in ngrams(entry['pos'].split(), 2) if not ("<" in n[0] and "<" in n[1])]
    for gram in pos2grams: 
        if gram not in GRAMS['pos2grams']: GRAMS['pos2grams'][gram] = 0 
        GRAMS['pos2grams'][gram] += 1 
    # get character quadrigrams of the lemmata 
    chars = []
    for word in entry['lemmata'].lower().split(): 
        if "<" in word and ">" in word: 
            chars.append(word)
        elif ".." not in word: 
            for c in word: 
                chars.append(c)
        chars.append("_")
    chars = chars[:-1]
    char4grams = ["".join(n) for n in ngrams(chars, 4) if len([x for x in n if "<" in x]) < 2]
    for gram in char4grams: 
        if gram not in GRAMS['char4grams']: GRAMS['char4grams'][gram] = 0 
        GRAMS['char4grams'][gram] += 1 
    # get entities with spacy 
    doc = NER(entry['lemmata'])
    for ent in doc.ents:
        entities.update({ent.label_})
        gram_key = f"entities_{ent.label_}"
        if gram_key not in GRAMS: GRAMS[gram_key] = {}
        if ent.text not in GRAMS[gram_key]: GRAMS[gram_key][ent.text] = 0 
        GRAMS[gram_key][ent.text] += 1 
        if ent.label_ not in FEATURES_DICT[key]: FEATURES_DICT[key][ent.label_] = 0 
        FEATURES_DICT[key][ent.label_] += 1 
    # get other features 
    t_list, pos_list, l_list = entry['tokens'].split(" "),entry['pos'].split(" "),entry['lemmata'].split(" ")
    curr_spans = { # start: [end, False, span]
        '<l>': {'end_tag': '</l>','in_span': False, 'span':reinitiate_spans()}, 
        '<i>': {'end_tag': '</i>','in_span': False, 'span':reinitiate_spans()},
        '<n>': {'end_tag': '</n>','in_span': False, 'span':reinitiate_spans()},
    }
    pos_spans = {
        'np': {'span':reinitiate_spans()}
    }
    curr_s_len = 0
    for t, p, l in zip(t_list, pos_list, l_list): 
        # LOWER CASE AND STRIP HYPHENS 
        t,p,l = t.lower(), p.lower(), l.lower()
        t = re.sub("-","",t)
        l = re.sub("-","",l)
        if ".." not in p: # ignore dividers 
            if t == "</s>": # end of a sentence 
                FEATURES_DICT[key]['sentence_length'].append(curr_s_len)
                curr_s_len = 0 # reset 
            elif t != "<s>": # not inclusive of boundaries 
                curr_s_len += 1 # not including <s> tags 
                FEATURES_DICT[key] = count_feature(l,p,FEATURES_DICT[key])
                lemma_key = (l,p)
                FEATURES_DICT[key]['num_types'].update({t})
                if re.search(content,p): # content word  
                    if lemma_key not in VOCAB['content']: VOCAB['content'][lemma_key] = 0 
                    VOCAB['content'][lemma_key] += 1 
                elif l==p: 
                    if lemma_key not in VOCAB['punctuation']: VOCAB['punctuation'][lemma_key] = 0 
                    VOCAB['punctuation'][lemma_key] += 1 
                else: 
                    if lemma_key not in VOCAB['function']: VOCAB['function'][lemma_key] = 0 
                    VOCAB['function'][lemma_key] += 1 
        for tag in curr_spans.keys(): 
            if tag == t: # start of a new span 
                curr_spans[tag]['in_span'] = True 
            elif t == curr_spans[tag]['end_tag']: # end of the span 
                # add to master dict 
                c = curr_spans[tag]['span']
                c = (c['tokens'].strip(),c['pos'].strip(),c['lemmata'].strip()) # convert list to tuple to use as key 
                if c not in SPANS[tag]: SPANS[tag][c] = 0 
                SPANS[tag][c] += 1 # keep a tally to rank by frequency later 
                curr_spans[tag]['in_span'] = False # reset flag 
                curr_spans[tag]['span'] = reinitiate_spans() # reset span 
            elif curr_spans[tag]['in_span']: # a lemma in the span 
                curr_spans[tag]['span'] = update_span(curr_spans[tag]['span'], t,p,l)
        for tag in pos_spans.keys(): 
            if tag in p: # same pos tag 
                pos_spans[tag]['span'] = update_span(pos_spans[tag]['span'], t,p,l)
            elif tag not in p:  
                c = pos_spans[tag]['span']
                if len(c['tokens']) > 0: 
                    c = (c['tokens'].strip(),c['pos'].strip(),c['lemmata'].strip()) # convert list to tuple to use as key 
                    if c not in SPANS[tag]: SPANS[tag][c] = 0 
                    SPANS[tag][c] += 1 # keep a tally to rank by frequency later 
                pos_spans[tag]['span'] = reinitiate_spans() # reset tag

In [195]:
from statistics import mean
not_pos_features = {"content","function","punctuation","female_pronouns","male_pronouns","plural_pronouns",
                    "sentence_length","paragraph_length","type_token_ratio"}
excluded = ["num_tokens","num_types"]
not_pos_features.update(entities)
features_df = []
# total_tokens = {} # tcpID to number of tokens 
# for key, f in FEATURES_DICT.items():
#     tcpID = key[0]
#     if tcpID not in total_tokens: total_tokens[tcpID] = 0
#     total_tokens[tcpID] += f['num_tokens']

for key, f in FEATURES_DICT.items(): 
    if len(f['sentence_length']) == 0: continue 
    value = {'tcpID':key[0],'curr_div_idx':key[1]}
    value['type_token_ratio'] = len(f['num_types']) / f['num_tokens']
    num_pns = f['female_pronouns'] + f['male_pronouns'] + f['plural_pronouns']
    num_entities = sum([freq for ent,freq in f.items() if ent in entities])
    for item,freq in f.items(): 
        if item in ["paragraph_length","sentence_length"]: 
            value[item] = mean(f[item])
        # elif item == "num_types": 
        #     value[item] = len(freq)
        # elif item == "num_tokens": 
        #     value[item] = freq
        elif item in excluded: continue 
        elif item in ["female_pronouns","male_pronouns","plural_pronouns"]: 
            if num_pns > 0: 
                value[item] = freq / num_pns
            else: 
                value[item] = 0 
        elif item in entities: 
            if num_entities > 0: 
                value[item] = freq / num_entities
            else: 
                value[item] = 0 
        elif item in ["content","function","punctuation"]:
            value[item] = freq / f['num_tokens']
        else: 
            value[item] = freq / f['num_tokens']
    features_df.append(value)
features_df = pd.DataFrame(features_df)
features_df = features_df.fillna(0)
features_df.to_csv("../features/ground_features.csv",index=False)
print(features_df[[col for col in features_df.columns if col in not_pos_features]][:3])
# features_df[[col for col in features_df.columns if col in entities]]
features_df

   type_token_ratio  sentence_length   content  function  punctuation  \
0          0.322214        21.567797  0.501895  0.391585     0.106520
1          0.319269        10.404412  0.497187  0.312940     0.189873
2          0.308742        21.489130  0.495200  0.368873     0.135927

   female_pronouns  male_pronouns  plural_pronouns  CARDINAL      NORP  \
0              0.0       0.285714         0.714286  0.462366  0.107527
1              0.0       0.611111         0.388889  0.611650  0.077670
2              0.0       0.800000         0.200000  0.607843  0.019608

     PERSON   ORDINAL       GPE      DATE   PRODUCT       ORG       LOC  \
0  0.225806  0.086022  0.032258  0.064516  0.010753  0.010753  0.000000
1  0.203883  0.009709  0.038835  0.058252  0.000000  0.000000  0.000000
2  0.117647  0.019608  0.019608  0.117647  0.019608  0.039216  0.019608

   QUANTITY
0  0.000000
1  0.000000
2  0.019608

,tcpID,curr_div_idx,type_token_ratio,sentence_length,content,function,punctuation,female_pronouns,male_pronouns,plural_pronouns,...,PRODUCT,ORG,:,\,(,),*,?,LOC,QUANTITY
0,DDC_FINAL,1,0.322214,21.567797,0.501895,0.391585,0.106520,0.0,0.285714,0.714286,...,0.010753,0.010753,0.000758,0.000758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,DDC_FINAL,3,0.319269,10.404412,0.497187,0.312940,0.189873,0.0,0.611111,0.388889,...,0.000000,0.000000,0.002813,0.000000,0.001406,0.001406,0.005626,0.000000,0.000000,0.000000
2,DDC_FINAL,4,0.308742,21.489130,0.495200,0.368873,0.135927,0.0,0.800000,0.200000,...,0.019608,0.039216,0.001011,0.000000,0.000505,0.000505,0.000000,0.001011,0.019608,0.019608

In [196]:
spans_df = []
for tag,items in SPANS.items(): 
    for parts,freq in items.items(): 
        value = {'tag':tag,'frequency':freq, 'tokens':parts[0],'pos': parts[1],'lemmata':parts[2]}
        spans_df.append(value)
spans_df = pd.DataFrame(spans_df)
spans_df = spans_df.sort_values(by=['frequency'],ascending=False)
spans_df.to_csv("../features/ground_spans.csv",index=False)
# spans_df[spans_df['tag']=="np"]
spans_df

,tag,frequency,tokens,pos,lemmata
70,np,61,god,np1,god
72,np,21,chap.,np1,chap.
78,np,12,christ,np1,christ
92,np,7,rom.,np1,rom.
106,np,6,tim.,np1,tim.
...,...,...,...,...,...
37,<i>,1,"be ye doers of the word , and not hearers only...","vbb pn22 n2 pp-f dt n1 , cc xx n2 av-j . </s> <s>","be you doer of the word , and not hearer only ..."
36,<i>,1,"not the hearers of the law , but the doers of ...","xx dt n2 pp-f dt n1 , cc-acp dt n2 pp-f dt n1 ...","not the hearer of the law , but the doer of th..."
35,<i>,1,that we should believe and love . </s> <s>,cst pns12 vmd vvi cc vvi . </s> <s>,that we shall believe and love . </s> <s>
34,<i>,1,that they which have believed might be careful,cst pns32 r-crq vhb vvn vmd vbi j,that they which have believe may be careful
126,np,1,adam,np1,adam

In [197]:
grams_df = []
for tag,items in GRAMS.items(): 
    for gram,freq in items.items(): 
        value = {'tag':tag,'frequency':freq, 'gram':gram}
        grams_df.append(value)
grams_df = pd.DataFrame(grams_df)
grams_df = grams_df.sort_values(by=['frequency'],ascending=False)
grams_df.to_csv("../features/ground_grams.csv",index=False)
print(entities)
print(grams_df[grams_df['tag'].str.contains("entities")])
print(grams_df)

{'GPE', 'PRODUCT', 'QUANTITY', 'ORDINAL', 'LOC', 'PERSON', 'CARDINAL', 'NORP', 'ORG', 'DATE'}
                    tag  frequency       gram
8168      entities_NORP         12  christian
8135  entities_CARDINAL         12        two
8099  entities_CARDINAL          9          1
8200   entities_ORDINAL          7      first
8138  entities_CARDINAL          7         17
...                 ...        ...        ...
8193    entities_PERSON          1       xvii
8190    entities_PERSON          1        Dan
8191    entities_PERSON          1   μόρφωσις
8192    entities_PERSON          1    Ephesus
8231  entities_QUANTITY          1   1 Sam xv

[133 rows x 3 columns]
                    tag  frequency      gram
37           char4grams        428      _the
38           char4grams        345      the_
34           char4grams        332      _of_
10           char4grams        304   ._</s>_
9            char4grams        247   _._</s>
...                 ...        ...       ...
4713         char4grams          1      ed_f
4712         char4grams          1      ceed
4711         char4grams          1      ocee
4710         char4grams          1      roce
8231  entities_QUANTITY          1  1 Sam xv

[8232 rows x 3 columns]

In [198]:
vocab_df = []
for category,items in VOCAB.items(): 
    for key,freq in items.items(): 
        value = {'category':category,'frequency':freq, 'lemma':key[0],'pos': key[1]}
        vocab_df.append(value)
vocab_df = pd.DataFrame(vocab_df)
vocab_df = vocab_df.sort_values(by=['frequency'],ascending=False)
vocab_df.to_csv("../features/ground_vocab.csv",index=False)
vocab_df

         category  frequency      lemma   pos
1495  punctuation        362          ,     ,
1363     function        342        the    dt
1362     function        326         of  pp-f
1494  punctuation        243          .     .
1364     function        134        and    cc
...           ...        ...        ...   ...
637       content          1    context    n1
636       content          1      arise   vvb
633       content          1      leave   vvn
632       content          1   possible  av-j
754       content          1  recognise   vvb

[1508 rows x 4 columns]

## Author Wikidata Features
- {'entity_type','description','occupation', 'position held', 'religion or worldview', 'educated at'}
- unresolvable problem: I do not differentiate authors for bound volumes 
- exclude wikidata for mismatches using dates of birth & death 
- get most common content words in description
- collapse occupations & positions held into one column & get all unique tags: "occupations" 
- all unique tags in these columns: educated at, religion or worldview

In [328]:
wiki_cols = {'TCP_name_heading','entity_title','date of birth','date of death'}
wiki_features = {'entity_type','description','occupation', 'position held', 'religion or worldview', 'educated at'}
wiki_cols.update(wiki_features)
authors_wiki = pd.read_csv(f"../features/APS_authors_wiki.csv")
# only keep relevant feature columns 
authors_wiki = authors_wiki[[col for col in authors_wiki.columns if col in wiki_cols]]
authors_ids = pd.read_csv(f"../features/APS_authors.csv")
authors = pd.merge(authors_wiki, authors_ids, on="TCP_name_heading", how="inner")
authors[:2]

,TCP_name_heading,entity_type,entity_title,description,date of birth,date of death,occupation,position held,religion or worldview,educated at,original_ids
0,"John Milton, 1608-1674",PERSON,John Milton,English poet and civil servant (1608–1674),+1608-12-09T00:00:00Z,+1674-11-08T00:00:00Z,"['poet (Q49757)', 'writer (Q36180)', 'politici...",NaN,Anglicanism (Q6423963),"[""Christ's College (Q714717)"", ""St Paul's Scho...","Milton, John, 1608-1674.; Milton, John, 1608-1..."
1,"Charles Richard Sumner, 1790-1874",PERSON,Charles Sumner (bishop),Bishop of Winchester; Bishop of Llandaff (1790...,+1790-11-22T00:00:00Z,+1874-08-15T00:00:00Z,"['librarian (Q182436)', 'Anglican priest (Q340...","['Anglican Bishop of Winchester (Q1271558)', '...",Anglicanism (Q6423963),"['Eton College (Q192088)', 'Trinity College (Q...","Sumner, Charles Richard, 1790-1874"

In [329]:
authors = authors.fillna('')
author_dicts = authors.to_dict(orient='records')
# feature category to another dict that maps each original TCP author heading to another dict of its individual features 
WIKI_FEATURES_ALL = {}
TOP_FEATURES = {}
for entry in author_dicts: 
    # check if the dates for the linked entity align with that of the TCP name heading 
    TCP_dates = re.findall(r"\d{4}",entry['TCP_name_heading'])
    wiki_dates = re.findall(r"\d{4}",entry['date of birth'])
    wiki_dates.extend(re.findall(r"\d{4}",entry['date of death']))
    to_skip = True 
    for year in TCP_dates: 
        if year in wiki_dates: 
            to_skip = False 
    if re.search("publisher|engraver|printer|bookseller", entry['original_ids']): continue 
    if to_skip: continue 
    feature_dict = {}
    description = re.sub(r"[^A-Za-z\s]+", "", entry['description'].lower()).split() # lower case and strip dates
    occupations = re.findall("[\'\"](.*?)[\'\"]",entry['occupation']) 
    occupations.extend(re.findall("[\'\"](.*?)[\'\"]",entry['position held']) )
    # get TCP original author headings 
    def update_dict(feature_dict,item,feature): 
        if item == "": return feature_dict
        feature_key = f"{item} ({feature})"
        if feature_key not in feature_dict: feature_dict[feature_key] = 0
        feature_dict[feature_key] += 1  
        if feature_key not in TOP_FEATURES: TOP_FEATURES[feature_key] = 0 
        TOP_FEATURES[feature_key] += 1 
        return feature_dict
    
    for token in description: # # count description tokens 
        feature_dict = update_dict(feature_dict,token, 'author\'s description')
    feature_dict = update_dict(feature_dict, entry['religion or worldview'],'author\'s religion or worldview')
    for item in occupations: 
        feature_dict = update_dict(feature_dict, item,'author\'s occupations')
    # create a separate entry for each unique heading 
    for heading in entry['original_ids'].split("; "):
        WIKI_FEATURES_ALL[heading] = feature_dict

TOP_FEATURES = [{'feature':k, 'frequency':v} for k,v in TOP_FEATURES.items()]
TOP_FEATURES = pd.DataFrame(TOP_FEATURES)
TOP_FEATURES = TOP_FEATURES.sort_values(by=['frequency'],ascending=False)
TOP_FEATURES = TOP_FEATURES[:133]['feature'].to_list()
TOP_FEATURES = set(TOP_FEATURES)       
        
WIKI_df = []
for heading,items in WIKI_FEATURES_ALL.items(): 
    info_dict = {'TCP_name_heading':heading}
    for feature_heading, freq in items.items():
        if feature_heading not in TOP_FEATURES: continue 
        info_dict[feature_heading] = freq
    WIKI_df.append(info_dict)
WIKI_df = pd.DataFrame(WIKI_df)
WIKI_df = WIKI_df.fillna(0)
WIKI_df.to_csv("../features/AUTHORS_WIKI_FEATURES.csv", index=False)
WIKI_df

,TCP_name_heading,english (author's description),poet (author's description),and (author's description),Anglicanism (Q6423963) (author's religion or worldview),poet (Q49757) (author's occupations),writer (Q36180) (author's occupations),politician (Q82955) (author's occupations),bishop (author's description),of (author's description),...,courtier (author's description),in (author's description),mathematician (author's description),astrologer (author's description),astronomer (Q11063) (author's occupations),antiquarian (author's description),archbishop (author's description),Lord Deputy of Ireland (Q3087864) (author's occupations),diplomat (author's description),physicist (Q169470) (author's occupations)
0,"Milton, John, 1608-1674.",1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,"Milton, John, 1608-1674. Samson Agonistes.",1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"Milton, John, 1608-1674. Paradise lost.",1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,"Sumner, Charles Richard, 1790-1874",0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"Collinges, John, 1623-1690.",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1811,"Pakington, Dorothy Coventry, Lady, d. 1679.",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1812,"Henchman, Humphrey, 1592-1675.",0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1813,"Gentili, Robert, 1590-1654?",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1814,"Desmarets de Saint-Sorlin, Jean, 1595-1676.",0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1815,"Baudier, Michel, 1589?-1645.",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [336]:
aut_list = pd.read_csv("../CORPUS/APS_METADATA_ground.csv").to_dict(orient='records')
aut_list.extend(pd.read_csv("../CORPUS/APS_METADATA_unknown.csv").to_dict(orient='records'))
tcpID_aut = []
for item in aut_list: 
    for aut in item['authors'].split("; "): 
        tcpID_aut.append({'tcpID': item['id'], 'author': aut})
tcpID_aut = pd.DataFrame(tcpID_aut)
tcpID_aut.to_csv("../CORPUS/tcpID_to_author.csv",index=False)
tcpID_aut

           tcpID                              author
0      DDC_FINAL            Milton, John, 1608-1674.
1      DDC_FINAL  Sumner, Charles Richard, 1790-1874
2         B08803         Collinges, John, 1623-1690.
3         B08178              Tuke, Thomas, d. 1657.
4         A95924        Vilvain, Robert, 1575?-1663.
...          ...                                 ...
12066     A25723            Davies, John, 1625-1693.
12067     A25723            Appianus, of Alexandria.
12068     A25723            Dryden, John, 1631-1700.
12069     A22627         Watts, William, 1590?-1649.
12070     A22627  Augustine, Saint, Bishop of Hippo.

[12071 rows x 2 columns]

# FULL FEATURE VECTORS FOR GROUND SET

Enhance FEATURES_DICT using the high-frequency features from VOCAB, SPANS, GRAMS and author wikidata

-- ALREADY ACQUIRED 
- average type-token ratio (vocab diversity)
- mean sentence length to all tokens 
- relative frequency of gendered pronouns: he, she, they (lemmata)
- proportion of content words to all tokens (lexical density)
- proportion of function words to all tokens 
- proportion of punctuation & boundaries to all tokens 
- relative frequencies of parts of speech

-- PENDING
- relative frequencies of 133 high-frequency        
    - function words to all words 
    - content words to all words 
    - punctuation to all words 
    - part-of-speech bigrams to all bigrams in the same book 
    - lemmata character 4-grams to all char 4-grams in the same book 
    - proper noun phrases to all noun phrases 
    - typographically emphasized phrases containing proper nouns  
    - author wikidata features (BOOLEAN)
- proportions of 
    - \<i\>, \<n\>, \<h\>, \<l\>, np, char4grams, pos2grams

-- WHY EXCLUDE ENTITIES? 
- originally going to use the 133 top capitalized entities (across all entity types)
- but NER with spacy took 2 hours for the ground dataset (a total of 83 books)
- there are 1096 books with sermons and 7409 remaining books --> it would take over 200 hours of continuous processing to get all the entities 
- the goal of the project is to filter those massive "unknown" and "sermon" sets to perform NER on core texts

In [3]:
ground = pd.read_csv("../CORPUS/APS_METADATA_ground.csv")['id'].to_list()
spans_df = pd.read_csv("../features/ground_spans.csv")
vocab_df = pd.read_csv("../features/ground_vocab.csv")
grams_df = pd.read_csv("../features/ground_grams.csv")
authors_df = pd.read_csv("../features/AUTHORS_WIKI_FEATURES.csv")

In [337]:
entities_features = grams_df[grams_df['tag'].str.contains("entities")][:500]
entities_features = entities_features[entities_features['gram'].str[0].str.isupper()]
entities_features

                   tag  frequency          gram
3212   entities_PERSON       4380          Paul
3587     entities_NORP       3832           Jew
3739   entities_PERSON       3624          John
4303   entities_PERSON       3084  Jesus Christ
4874     entities_NORP       2626    Christians
...                ...        ...           ...
27888     entities_ORG         80        Apostl
27914  entities_PERSON         80          Josh
27921     entities_ORG         80         Iames
27997     entities_ORG         79        Justin
28048     entities_GPE         79       Samaria

[133 rows x 3 columns]

In [8]:
high_freq_features = { # get lemma column 
                       'Content words':vocab_df[vocab_df['category']=="content"][:133],
                       'Function words':vocab_df[vocab_df['category']=="function"][:133],
                       'Punctuation and boundaries':vocab_df[vocab_df['category']=="punctuation"][:133],
                       # get gram column 
                       'Character quadrigrams':grams_df[grams_df['tag']=="char4grams"][:133],
                       'Part-of-speech bigrams':grams_df[grams_df['tag']=="pos2grams"][:133],
                       # get lemmata column 
                       'Noun Phrases':spans_df[spans_df['tag']=="np"][:133],
                       'Italicized Spans':spans_df[spans_df['tag']=="<i>"][:133]
}
NEW_FEATURES = [{'tag':'author_wiki','item':item} for item in list(authors_df.columns)[1:]]
for tag, df in high_freq_features.items(): 
    print(tag)
    print(df[:10])
    print()
    if "lemma" in df.columns: 
        to_add = 'lemma'
    elif "lemmata" in df.columns: 
        to_add = 'lemmata'
    elif 'gram' in df.columns: 
        to_add = 'gram'
    NEW_FEATURES.extend([{'tag':tag,'item':item} for item in list(df[to_add])])
NEW_FEATURES = pd.DataFrame(NEW_FEATURES)
NEW_FEATURES.to_csv("../features/HIGH_FREQ_FEATURES.csv",index=False)
print(NEW_FEATURES[NEW_FEATURES['tag']=="author_wiki"])

Content words
   category  frequency         lemma  pos
8   content     148076      be (vbz)  vbz
18  content      79532      be (vbi)  vbi
19  content      70396     god (np1)  np1
29  content      55078      be (vbr)  vbr
32  content      44645       so (av)   av
43  content      33176  christ (np1)  np1
49  content      25114      man (n1)   n1
50  content      25086     may (vmb)  vmb
53  content      24658    have (vhb)  vhb
54  content      24336   shall (vmb)  vmb

Function words
    category  frequency        lemma     pos
1   function     532667     the (dt)      dt
4   function     376618    of (pp-f)    pp-f
5   function     318709     and (cc)      cc
7   function     182271   in (p-acp)   p-acp
9   function     130280       a (dt)      dt
10  function     126812   that (cst)     cst
11  function     125353  to (pc-acp)  pc-acp
12  function     108656   to (p-acp)   p-acp
13  function     104773    it (pn31)    pn31
15  function      82308     not (xx)      xx

Punctuation and boundaries
       category  frequency        lemma   pos
0   punctuation     818753        , (,)     ,
2   punctuation     412124    <i> (<i>)   <i>
3   punctuation     412117  </i> (</i>)  </i>
6   punctuation     304304        . (.)     .
14  punctuation      93861        ; (;)     ;
21  punctuation      68963        : (:)     :
41  punctuation      33684    <n> (<n>)   <n>
42  punctuation      33684  </n> (</n>)  </n>
51  punctuation      24734        ( (()     (
52  punctuation      24706        ) ())     )

Character quadrigrams
           tag  frequency     gram
0   char4grams     761148     _the
1   char4grams     533799     the_
2   char4grams     418663  ._</s>_
3   char4grams     387396     _be_
4   char4grams     376606     _of_
5   char4grams     343963     and_
7   char4grams     319472     _and
8   char4grams     292064  _._</s>
11  char4grams     234011     _to_
14  char4grams     186537     e_,_

Part-of-speech bigrams
          tag  frequency         gram
6   pos2grams     330168        dt_n1
9   pos2grams     292064       ._</s>
10  pos2grams     280901         n1_,
12  pos2grams     208133      n1_pp-f
13  pos2grams     200914     p-acp_dt
23  pos2grams     135065         ,_cc
25  pos2grams     127624         j_n1
27  pos2grams     122317  fw-la_fw-la
34  pos2grams     109636      <i>_np1
36  pos2grams     107023     n1_p-acp

Noun Phrases
  tag  frequency   tokens   pos lemmata
0  np      70244      god   np1     god
1  np      29380   christ   np1  christ
2  np       8037     gods  npg1     god
3  np       5054     rom.   np1    rom.
4  np       4892     cor.   np1    cor.
5  np       4577    psal.   np1   psal.
6  np       3834  christs  npg1  christ
7  np       3297     paul   np1    paul
8  np       2971    moses   np1   moses
9  np       2932     john   np1    john

Italicized Spans
    tag  frequency tokens  pos lemmata
13  <i>       2231   cor.  np1    cor.
16  <i>       2104   rom.  np1    rom.
19  <i>       1959  psal.  np1   psal.
26  <i>       1647   viz.   n1    viz.
29  <i>       1558   paul  np1    paul
34  <i>       1373  moses  np1   moses
35  <i>       1319    &c.   av     etc
42  <i>       1127   john  np1    john
43  <i>       1114   heb.  np1    heb.
45  <i>       1063    god  np1     god

             tag                                               item
0    author_wiki                     english (author's description)
1    author_wiki                        poet (author's description)
2    author_wiki                         and (author's description)
3    author_wiki  Anglicanism (Q6423963) (author's religion or w...
4    author_wiki               poet (Q49757) (author's occupations)
..           ...                                                ...
128  author_wiki                 antiquarian (author's description)
129  author_wiki                  archbishop (author's description)
130  author_wiki  Lord Deputy of Ireland (Q3087864) (author's oc...
131  author_wiki                    diplomat (author's description)
132  author_wiki         physicist (Q169470) (author's occupations)

[133 rows x 2 columns]

In [296]:
FEATURES = pd.read_csv("../features/ground_features.csv")
print(len(FEATURES.columns) + len(NEW_FEATURES))
FEATURES

897

,tcpID,curr_div_idx,type_token_ratio,sentence_length,content,function,punctuation,female_pronouns,male_pronouns,plural_pronouns,...,/,☞,**,☜,†,·,`,•••••,=,••••
0,DDC_FINAL,1,0.322214,21.567797,0.501895,0.391585,0.106520,0.000000,0.285714,0.714286,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
1,DDC_FINAL,3,0.319269,10.404412,0.497187,0.312940,0.189873,0.000000,0.611111,0.388889,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
2,DDC_FINAL,4,0.176975,10.461769,0.499643,0.298386,0.201971,0.000000,0.801653,0.198347,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
3,DDC_FINAL,5,0.198991,24.229947,0.519526,0.350154,0.130320,0.000000,0.541176,0.458824,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
4,DDC_FINAL,6,0.122814,18.919903,0.499298,0.333716,0.166986,0.002681,0.630027,0.367292,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3780,A02178,296,0.139002,38.532308,0.524551,0.339082,0.136367,0.020408,0.400510,0.579082,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00008
3781,A02178,297,0.195442,31.176101,0.522993,0.351755,0.125252,0.000000,0.370079,0.629921,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
3782,A02178,298,0.394231,52.000000,0.471154,0.365385,0.163462,0.000000,0.750000,0.250000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
3783,A02178,299,0.442901,40.500000,0.507716,0.348765,0.143519,0.000000,1.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
3784,A02178,300,0.094209,27.087611,0.516368,0.321197,0.162436,0.020653,0.467688,0.511659,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000